missing import
I got the following error:
File "/usr/local/lib/python3.5/dist-packages/PyZE-0.2.2-py3.5.egg/pyze/cli/charge-history.py", line 48, in _format_charge_history
NameError: name 'dateutil' is not defined

Fixed by adding these imports.